version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          checkout: true
          create-repo: true
          dockerfile: Dockerfile
          repo: amplify-cli-base-image
          tag: "latest"
