version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 744586199449.dkr.ecr.us-east-2.amazonaws.com/amplify-cli-base-image:latest

jobs:
  build_image:
    docker:
      - image: circleci/node:10.18
    steps:
      - aws-ecr/build-and-push-image:
          checkout: true
          create-repo: true
          dockerfile: Dockerfile
          repo: amplify-cli-base-image
          tag: "latest"
  test:
    <<: *defaults
    steps:
      - run: echo $PATH
      - run: java --version
      - run: gradle --version
      - run: go version
      - run: pipenv --version
      - run: dotnet tool list -g

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build_image
      - test:
          requires:
            - build_image
