version: 2.1
jobs:
  build_docker_image:
    docker:
      - image: circleci/node:10.18
        auth:
          username: yathib
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t yathib/test-hub:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push yathib/test-hub:$TAG
workflows:
  version: 2
  jobs:
    - build_docker_image
